server:
  port: 8071
  servlet:
    context-path: /manager
spring:
  application:
    name: duc-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://127.0.0.1:3306/duc?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 920526770
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 500
    initialSize: 20
    minIdle: 10
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    validationInterval: 30000
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    removeAbandonedTimeout: 300
    jdbcInterceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer
  rocketmq:
    name-server-address: 10.12.52.34:9876;10.12.52.35:9876
    # 可选, 如果无需发送消息则忽略该配置
    producer-group: local_pufang_producer
    # 发送超时配置毫秒数, 可选, 默认3000
    send-msg-timeout: 5000
    # 追溯消息具体消费情况的开关，默认打开
    trace-enabled: false
    # 是否启用VIP通道，默认打开
    #vip-channel-enabled: false

  redis:
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
          pool:
            max-active: 100
            max-idle: 10


logging:
  level:
    com:
      admin:
        source:
          mapper: trace

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true


security:
  matchers[0]: /css/**
  matchers[1]: /fonts/**
  matchers[2]: /images/**
  matchers[3]: /js/**
  matchers[4]: /lib/**
  matchers[5]: /layui/**
  loginPage: /login
  logoutUrl: /logout
  logoutSuccessUrl: /login
  secret: MD5